all:
	c++ -std=c++17 -o bin/NodeTest.exe test/NodeTest.cpp src/Node.cpp -Wno-unused-variable
	c++ -std=c++17 -o bin/NodeListTest.exe test/NodeListTest.cpp src/Node.cpp src/NodeList.cpp -Wno-unused-variable
	